name: Deploy Frontend to Azure

on:
  push:
    branches:
      - main  # Change if using a different branch
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install
        working-directory: frontend

      - name: Create .env File
        run: |
          echo "VITE_API_BASE_URL=http://44.203.193.5:5000/api" > frontend/.env
        working-directory: frontend

      - name: Build Project
        run: npm run build
        working-directory: frontend

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "frontend"  # Folder where frontend is located
          output_location: "frontend/dist"  # Build folder output
