name: CI/CD Pipeline for Multi-Cloud Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # ✅ FRONTEND: Deploy to Azure Static Web Apps
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # ✅ Ensure this matches the required version for react-router

      - name: Install Dependencies
        run: |
          cd frontend
          npm install

      - name: Build Frontend
        run: |
          cd frontend
          npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} 
          action: "upload"
          app_location: "frontend"    # ✅ Points to your frontend code
          output_location: "dist"      # ✅ Vite’s build output folder

  